// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
// /// // ...
// await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTtxsW4l36QEnAKyanQ4flb_-t0A6Kmu0',
    appId: '1:309634813442:web:4ca68e2010384650eae11b',
    messagingSenderId: '309634813442',
    projectId: 'testproj-fltr-notesproj',
    authDomain: 'testproj-fltr-notesproj.firebaseapp.com',
    storageBucket: 'testproj-fltr-notesproj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2bjjNCmvrAQxRZt1ZJK60VsOxivMLdM',
    appId: '1:309634813442:android:063fbb54143768e6eae11b',
    messagingSenderId: '309634813442',
    projectId: 'testproj-fltr-notesproj',
    storageBucket: 'testproj-fltr-notesproj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUXrhgl5uwxZPM-MYgdLn1mMwXuVUmR9o',
    appId: '1:309634813442:ios:0b041154038e4b7deae11b',
    messagingSenderId: '309634813442',
    projectId: 'testproj-fltr-notesproj',
    storageBucket: 'testproj-fltr-notesproj.appspot.com',
    iosBundleId: 'com.example.testProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUXrhgl5uwxZPM-MYgdLn1mMwXuVUmR9o',
    appId: '1:309634813442:ios:b525dd1680460b9ceae11b',
    messagingSenderId: '309634813442',
    projectId: 'testproj-fltr-notesproj',
    storageBucket: 'testproj-fltr-notesproj.appspot.com',
    iosBundleId: 'com.example.testProj.RunnerTests',
  );
}
